create table if not exists public.event_audit_logs (
  id bigint generated by default as identity primary key,
  event_id text not null,
  event_title text not null default '',
  action text not null check (action in ('insert', 'update', 'delete')),
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default '系统',
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists event_audit_logs_created_at_idx
  on public.event_audit_logs (created_at desc);
create index if not exists event_audit_logs_event_id_idx
  on public.event_audit_logs (event_id);

alter table public.event_audit_logs enable row level security;

drop policy if exists "authenticated read event audit logs" on public.event_audit_logs;
create policy "authenticated read event audit logs"
  on public.event_audit_logs for select to authenticated
  using (true);

create or replace function public.audit_event_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_label text;
  target_id text;
  target_title text;
begin
  select coalesce(nullif(p.full_name, ''), split_part(u.email, '@', 1), '系统')
    into actor_label
    from auth.users u
    left join public.profiles p on p.id = u.id
   where u.id = auth.uid();

  target_id := case when tg_op = 'DELETE' then old.id else new.id end;
  target_title := case when tg_op = 'DELETE' then old.title else new.title end;

  insert into public.event_audit_logs (
    event_id, event_title, action, actor_id, actor_name, old_data, new_data
  )
  values (
    target_id,
    target_title,
    lower(tg_op),
    auth.uid(),
    coalesce(actor_label, '系统'),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists events_audit_change on public.events;
create trigger events_audit_change
after insert or update or delete on public.events
for each row execute function public.audit_event_change();

do $$ begin
  alter publication supabase_realtime add table public.event_audit_logs;
exception when duplicate_object then null;
end $$;
