-- Run this whole file once in Supabase SQL Editor.
-- It is safe to run again.

insert into public.profiles (id, full_name)
select
  u.id,
  coalesce(u.raw_user_meta_data->>'full_name', split_part(u.email, '@', 1), '')
from auth.users u
on conflict (id) do nothing;

create or replace function public.admin_list_accounts()
returns table (
  user_id uuid,
  email text,
  full_name text,
  role public.app_role,
  person_id text,
  person_name text,
  last_sign_in_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.current_app_role() <> 'admin' then
    raise exception 'Only administrators can manage accounts';
  end if;

  return query
  select
    u.id,
    u.email::text,
    p.full_name,
    p.role,
    p.person_id,
    pe.name,
    u.last_sign_in_at
  from auth.users u
  join public.profiles p on p.id = u.id
  left join public.people pe on pe.id = p.person_id
  order by u.email;
end;
$$;

create or replace function public.admin_update_account(
  target_user_id uuid,
  target_person_id text,
  target_role public.app_role
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  linked_name text;
begin
  if public.current_app_role() <> 'admin' then
    raise exception 'Only administrators can manage accounts';
  end if;

  if target_person_id is not null then
    select name into linked_name from public.people where id = target_person_id;
    if linked_name is null then
      raise exception 'Selected team member does not exist';
    end if;
  end if;

  update public.profiles
     set person_id = target_person_id,
         role = target_role,
         full_name = coalesce(linked_name, nullif(full_name, ''), '团队成员'),
         updated_at = now()
   where id = target_user_id;

  if not found then
    raise exception 'Account profile does not exist';
  end if;
end;
$$;

grant execute on function public.admin_list_accounts() to authenticated;
grant execute on function public.admin_update_account(uuid, text, public.app_role) to authenticated;

-- Recreate the audit feature so this migration also repairs installations
-- where the earlier audit SQL was not run completely.
create table if not exists public.event_audit_logs (
  id bigint generated by default as identity primary key,
  event_id text not null,
  event_title text not null default '',
  action text not null check (action in ('insert', 'update', 'delete')),
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default '系统',
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists event_audit_logs_created_at_idx
  on public.event_audit_logs (created_at desc);

alter table public.event_audit_logs enable row level security;
drop policy if exists "authenticated read event audit logs" on public.event_audit_logs;
create policy "authenticated read event audit logs"
  on public.event_audit_logs for select to authenticated using (true);

create or replace function public.audit_event_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_label text;
begin
  select coalesce(nullif(p.full_name, ''), split_part(u.email, '@', 1), '系统')
    into actor_label
    from auth.users u
    left join public.profiles p on p.id = u.id
   where u.id = auth.uid();

  insert into public.event_audit_logs (
    event_id, event_title, action, actor_id, actor_name, old_data, new_data
  )
  values (
    case when tg_op = 'DELETE' then old.id else new.id end,
    case when tg_op = 'DELETE' then old.title else new.title end,
    lower(tg_op),
    auth.uid(),
    coalesce(actor_label, '系统'),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists events_audit_change on public.events;
create trigger events_audit_change
after insert or update or delete on public.events
for each row execute function public.audit_event_change();

do $$ begin
  alter publication supabase_realtime add table public.events;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.people;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.groups;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.event_audit_logs;
exception when duplicate_object then null;
end $$;

create or replace function public.get_schedule_system_status()
returns table (
  audit_trigger_enabled boolean,
  events_realtime_enabled boolean,
  audit_realtime_enabled boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    exists (
      select 1 from pg_trigger
      where tgname = 'events_audit_change' and not tgisinternal
    ),
    exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'events'
    ),
    exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'event_audit_logs'
    );
$$;

grant execute on function public.get_schedule_system_status() to authenticated;

select
  'K-Loud upgrade installed' as result,
  exists (
    select 1 from pg_trigger
    where tgname = 'events_audit_change' and not tgisinternal
  ) as audit_trigger_enabled,
  exists (
    select 1 from pg_proc
    where proname = 'admin_list_accounts'
  ) as account_management_enabled;
