-- K-Loud shared cloud data model.
-- Run this entire file once in Supabase SQL Editor.
-- It migrates existing people/events data without re-seeding on refresh.

create extension if not exists pgcrypto;

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  groups text[] not null default '{}',
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.members (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  legacy_id text,
  name text not null,
  role text not null default '',
  group_name text not null default '未分组',
  color text not null default '#4778f5',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (team_id, legacy_id)
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  legacy_event_id text,
  title text not null,
  city text not null default '',
  business_type text not null default '未分类',
  venue text not null default '',
  notes text not null default '',
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (team_id, legacy_event_id)
);

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  member_id uuid not null references public.members(id) on delete restrict,
  start_at timestamp without time zone not null,
  end_at timestamp without time zone not null,
  status text not null check (status in ('confirmed', 'pending', 'progress', 'draft')),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint assignments_time_order check (end_at > start_at)
);

create table if not exists public.event_audit_logs (
  id bigint generated by default as identity primary key,
  event_id text not null,
  event_title text not null default '',
  action text not null check (action in ('insert', 'update', 'delete')),
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default '系统',
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists members_team_id_idx on public.members(team_id);
create index if not exists projects_team_id_idx on public.projects(team_id);
create index if not exists assignments_team_id_idx on public.assignments(team_id);
create index if not exists assignments_member_time_idx on public.assignments(member_id, start_at, end_at);

alter table public.profiles add column if not exists team_id uuid references public.teams(id) on delete set null;
alter table public.profiles add column if not exists member_id uuid references public.members(id) on delete set null;
alter table public.event_audit_logs add column if not exists team_id uuid references public.teams(id) on delete cascade;

do $$
declare
  default_team_id uuid;
begin
  select id into default_team_id from public.teams order by created_at limit 1;

  if default_team_id is null then
    insert into public.teams (name, groups)
    values ('K-Loud', array['业务一组','业务二组','演出组','内容组','商务组'])
    returning id into default_team_id;
  end if;

  update public.profiles set team_id = default_team_id where team_id is null;
  update public.event_audit_logs set team_id = default_team_id where team_id is null;

  if to_regclass('public.people') is not null then
    insert into public.members (team_id, legacy_id, name, role, group_name, color)
    select default_team_id, p.id, p.name, p.role, p.group_name, p.color
    from public.people p
    on conflict (team_id, legacy_id) do update
      set name = excluded.name,
          role = excluded.role,
          group_name = excluded.group_name,
          color = excluded.color,
          updated_at = now();
  end if;

  if to_regclass('public.events') is not null then
    insert into public.projects (
      team_id, legacy_event_id, title, city, business_type, venue, notes, created_by
    )
    select
      default_team_id, e.id, e.title, e.city, e.business_type, e.venue, e.notes, e.created_by
    from public.events e
    on conflict (team_id, legacy_event_id) do update
      set title = excluded.title,
          city = excluded.city,
          business_type = excluded.business_type,
          venue = excluded.venue,
          notes = excluded.notes,
          updated_at = now();

    insert into public.assignments (
      team_id, project_id, member_id, start_at, end_at, status, created_by
    )
    select
      default_team_id,
      pr.id,
      m.id,
      e.start_at,
      e.end_at,
      e.status,
      e.created_by
    from public.events e
    join public.projects pr
      on pr.team_id = default_team_id and pr.legacy_event_id = e.id
    join public.members m
      on m.team_id = default_team_id and m.legacy_id = e.owner_id
    where not exists (
      select 1 from public.assignments a where a.project_id = pr.id
    );
  end if;

  update public.profiles p
     set member_id = m.id
    from public.members m
   where p.team_id = m.team_id
     and p.person_id = m.legacy_id
     and p.member_id is null;
end
$$;

create or replace function public.current_team_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select team_id from public.profiles where id = auth.uid();
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  default_team_id uuid;
begin
  select id into default_team_id from public.teams order by created_at limit 1;
  insert into public.profiles (id, full_name, team_id)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1), ''),
    default_team_id
  )
  on conflict (id) do update
    set team_id = coalesce(public.profiles.team_id, excluded.team_id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at before update on public.teams
for each row execute function public.set_updated_at();
drop trigger if exists members_set_updated_at on public.members;
create trigger members_set_updated_at before update on public.members
for each row execute function public.set_updated_at();
drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects
for each row execute function public.set_updated_at();
drop trigger if exists assignments_set_updated_at on public.assignments;
create trigger assignments_set_updated_at before update on public.assignments
for each row execute function public.set_updated_at();

alter table public.teams enable row level security;
alter table public.members enable row level security;
alter table public.projects enable row level security;
alter table public.assignments enable row level security;
alter table public.event_audit_logs enable row level security;

drop policy if exists "team users read team" on public.teams;
create policy "team users read team" on public.teams for select to authenticated
using (id = public.current_team_id());
drop policy if exists "admins update team" on public.teams;
create policy "admins update team" on public.teams for update to authenticated
using (id = public.current_team_id() and public.current_app_role() = 'admin')
with check (id = public.current_team_id() and public.current_app_role() = 'admin');

drop policy if exists "team users read members" on public.members;
create policy "team users read members" on public.members for select to authenticated
using (team_id = public.current_team_id());
drop policy if exists "admins manage members" on public.members;
create policy "admins manage members" on public.members for all to authenticated
using (team_id = public.current_team_id() and public.current_app_role() = 'admin')
with check (team_id = public.current_team_id() and public.current_app_role() = 'admin');

drop policy if exists "team users read projects" on public.projects;
create policy "team users read projects" on public.projects for select to authenticated
using (team_id = public.current_team_id());
drop policy if exists "editors manage projects" on public.projects;
create policy "editors manage projects" on public.projects for all to authenticated
using (team_id = public.current_team_id() and public.current_app_role() in ('admin','editor'))
with check (team_id = public.current_team_id() and public.current_app_role() in ('admin','editor'));

drop policy if exists "team users read assignments" on public.assignments;
create policy "team users read assignments" on public.assignments for select to authenticated
using (team_id = public.current_team_id());
drop policy if exists "editors manage assignments" on public.assignments;
create policy "editors manage assignments" on public.assignments for all to authenticated
using (team_id = public.current_team_id() and public.current_app_role() in ('admin','editor'))
with check (team_id = public.current_team_id() and public.current_app_role() in ('admin','editor'));

drop policy if exists "authenticated read event audit logs" on public.event_audit_logs;
drop policy if exists "team users read event audit logs" on public.event_audit_logs;
create policy "team users read event audit logs" on public.event_audit_logs for select to authenticated
using (team_id = public.current_team_id());

create or replace function public.save_schedule(
  p_assignment_id uuid,
  p_project_id uuid,
  p_member_id uuid,
  p_title text,
  p_start_at timestamp without time zone,
  p_end_at timestamp without time zone,
  p_status text,
  p_city text,
  p_business_type text,
  p_venue text,
  p_notes text
)
returns table (assignment_id uuid, project_id uuid)
language plpgsql
security invoker
set search_path = public
as $$
declare
  active_team uuid := public.current_team_id();
  saved_project_id uuid;
  saved_assignment_id uuid;
begin
  if public.current_app_role() not in ('admin','editor') then
    raise exception 'Current account is read-only';
  end if;
  if active_team is null then raise exception 'Account is not assigned to a team'; end if;
  if not exists (select 1 from public.members where id = p_member_id and team_id = active_team) then
    raise exception 'Selected member does not belong to this team';
  end if;

  if p_project_id is null then
    insert into public.projects (team_id, title, city, business_type, venue, notes)
    values (active_team, p_title, coalesce(p_city,''), coalesce(p_business_type,'未分类'), coalesce(p_venue,''), coalesce(p_notes,''))
    returning id into saved_project_id;
  else
    update public.projects
       set title = p_title,
           city = coalesce(p_city,''),
           business_type = coalesce(p_business_type,'未分类'),
           venue = coalesce(p_venue,''),
           notes = coalesce(p_notes,'')
     where id = p_project_id and team_id = active_team
     returning id into saved_project_id;
    if saved_project_id is null then raise exception 'Project does not exist'; end if;
  end if;

  if p_assignment_id is null then
    insert into public.assignments (team_id, project_id, member_id, start_at, end_at, status)
    values (active_team, saved_project_id, p_member_id, p_start_at, p_end_at, p_status)
    returning id into saved_assignment_id;
  else
    update public.assignments
       set member_id = p_member_id,
           start_at = p_start_at,
           end_at = p_end_at,
           status = p_status
     where id = p_assignment_id and team_id = active_team
     returning id into saved_assignment_id;
    if saved_assignment_id is null then raise exception 'Assignment does not exist'; end if;
  end if;

  return query select saved_assignment_id, saved_project_id;
end;
$$;

create or replace function public.delete_schedule(p_assignment_id uuid)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  active_team uuid := public.current_team_id();
  linked_project uuid;
begin
  if public.current_app_role() not in ('admin','editor') then
    raise exception 'Current account is read-only';
  end if;

  delete from public.assignments
   where id = p_assignment_id and team_id = active_team
  returning project_id into linked_project;

  if linked_project is null then raise exception 'Assignment does not exist'; end if;
  if not exists (select 1 from public.assignments where project_id = linked_project) then
    delete from public.projects where id = linked_project and team_id = active_team;
  end if;
end;
$$;

grant execute on function public.save_schedule(
  uuid, uuid, uuid, text, timestamp without time zone, timestamp without time zone,
  text, text, text, text, text
) to authenticated;
grant execute on function public.delete_schedule(uuid) to authenticated;

drop function if exists public.admin_list_accounts();
create or replace function public.admin_list_accounts()
returns table (
  user_id uuid,
  email text,
  full_name text,
  role public.app_role,
  member_id uuid,
  member_name text,
  last_sign_in_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.current_app_role() <> 'admin' then
    raise exception 'Only administrators can manage accounts';
  end if;
  return query
  select u.id, u.email::text, p.full_name, p.role, p.member_id, m.name, u.last_sign_in_at
  from auth.users u
  join public.profiles p on p.id = u.id
  left join public.members m on m.id = p.member_id
  where p.team_id = public.current_team_id()
  order by u.email;
end;
$$;

drop function if exists public.admin_update_account(uuid, text, public.app_role);
drop function if exists public.admin_update_account(uuid, uuid, public.app_role);
create or replace function public.admin_update_account(
  target_user_id uuid,
  target_member_id uuid,
  target_role public.app_role
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  linked_name text;
begin
  if public.current_app_role() <> 'admin' then
    raise exception 'Only administrators can manage accounts';
  end if;
  if target_member_id is not null then
    select name into linked_name
    from public.members
    where id = target_member_id and team_id = public.current_team_id();
    if linked_name is null then raise exception 'Selected member does not belong to this team'; end if;
  end if;

  update public.profiles
     set member_id = target_member_id,
         person_id = null,
         role = target_role,
         full_name = coalesce(linked_name, nullif(full_name,''), '团队成员'),
         updated_at = now()
   where id = target_user_id and team_id = public.current_team_id();
  if not found then raise exception 'Account does not belong to this team'; end if;
end;
$$;

grant execute on function public.admin_list_accounts() to authenticated;
grant execute on function public.admin_update_account(uuid, uuid, public.app_role) to authenticated;

create or replace function public.audit_assignment_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_label text;
  project_title text;
  target_assignment_id uuid;
  target_project_id uuid;
begin
  target_assignment_id := case when tg_op = 'DELETE' then old.id else new.id end;
  target_project_id := case when tg_op = 'DELETE' then old.project_id else new.project_id end;
  select title into project_title from public.projects where id = target_project_id;
  select coalesce(nullif(p.full_name,''), split_part(u.email,'@',1), '系统')
    into actor_label
    from auth.users u left join public.profiles p on p.id = u.id
   where u.id = auth.uid();

  insert into public.event_audit_logs (
    team_id, event_id, event_title, action, actor_id, actor_name, old_data, new_data
  ) values (
    case when tg_op = 'DELETE' then old.team_id else new.team_id end,
    target_assignment_id::text,
    coalesce(project_title, '未命名项目'),
    lower(tg_op),
    auth.uid(),
    coalesce(actor_label,'系统'),
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
  );
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists assignments_audit_change on public.assignments;
create trigger assignments_audit_change
after insert or update or delete on public.assignments
for each row execute function public.audit_assignment_change();

do $$ begin alter publication supabase_realtime add table public.members;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.projects;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.assignments;
exception when duplicate_object then null; end $$;

drop function if exists public.get_schedule_system_status();
create or replace function public.get_schedule_system_status()
returns table (
  audit_trigger_enabled boolean,
  assignments_realtime_enabled boolean,
  projects_realtime_enabled boolean,
  members_realtime_enabled boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    exists (select 1 from pg_trigger where tgname = 'assignments_audit_change' and not tgisinternal),
    exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='assignments'),
    exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='projects'),
    exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='members');
$$;

grant execute on function public.get_schedule_system_status() to authenticated;

select
  'K-Loud cloud data model installed' as result,
  (select count(*) from public.teams) as teams,
  (select count(*) from public.members) as members,
  (select count(*) from public.projects) as projects,
  (select count(*) from public.assignments) as assignments;
